name: Project CI/CD

on:
  push:
    branches: [main]
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write # Needed for CodeQL to upload SARIF

jobs:
  call-shared-pipeline:
    uses: LuisDio/secops-shared-workflow/.github/workflows/shared-devsecops.yml@main
    with:
      app-name: my-awesome-app
      language: javascript

  codeql:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: CodeQL Init
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v3
